const categories = [
  { id: 1, name: "General" },
  { id: 2, name: "HTML" },
  { id: 3, name: "HTML Basics" },
  { id: 4, name: "HTML Elements" },
  { id: 5, name: "HTML Forms" },
  { id: 6, name: "HTML Images" },
  { id: 7, name: "HTML Links" },
  { id: 8, name: "CSS" },
  { id: 9, name: "CSS Basics" },
  { id: 10, name: "CSS Selectors" },
  { id: 11, name: "CSS Layout" },
  { id: 12, name: "CSS Box Model" },
  { id: 13, name: "CSS Typography" },
  { id: 14, name: "CSS Colors" },
  { id: 15, name: "JavaScript" },
  { id: 16, name: "JavaScript Basics" },
  { id: 17, name: "JavaScript Variables" },
  { id: 18, name: "JavaScript Functions" },
  { id: 19, name: "JavaScript Events" },
  { id: 20, name: "JavaScript DOM Manipulation" },
  { id: 21, name: "JavaScript Conditions and Loops" },
  { id: 22, name: "React" },
  { id: 23, name: "React Basics" },
  { id: 24, name: "React Components" },
  { id: 25, name: "React Props and State" },
  { id: 26, name: "React Events and Handling" },
  { id: 27, name: "React Hooks" },
  { id: 28, name: "React Forms" },
  { id: 29, name: "MongoDB" },
  { id: 30, name: "MongoDB Basics" },
  { id: 31, name: "MongoDB CRUD Operations" },
  { id: 32, name: "MongoDB Queries" },
  { id: 33, name: "MongoDB Aggregation" },
  { id: 34, name: "MongoDB Indexes" },
  { id: 35, name: "MongoDB Atlas" },
  { id: 36, name: "Node.js" },
  { id: 37, name: "Node.js Basics" },
  { id: 38, name: "Node.js Modules" },
  { id: 39, name: "Node.js File System" },
  { id: 40, name: "Node.js HTTP Module" },
  { id: 41, name: "Node.js NPM" },
  { id: 42, name: "Node.js Express" },
  { id: 43, name: "Express" },
  { id: 44, name: "Express Basics" },
  { id: 45, name: "Express Routing" },
  { id: 46, name: "Express Middleware" },
  { id: 47, name: "Express Templating" },
  { id: 48, name: "Express Forms Handling" },
  { id: 49, name: "Express REST API" },
];

export default categories;
